"use client";
import "./globals.css";
import Loging from "./Loging/page";
import { useState } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [User, setUser] = useState(null);

  return (
    <html lang="en">
      {/* {(User && <body>{children}</body>) || <Loging setUser={setUser} />} */}
      <body>{children}</body>
    </html>
  );
}
